//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class BatchMasterBase
    {
        public int BatchMasterID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Code { get; set; }
        public decimal PlannedQuantity { get; set; }
        public int PackQuantity { get; set; }
        public decimal PackLineVolume { get; set; }
        public string BatchStatusCode { get; set; }
        public string Remarks { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public string CommodityAPICode { get; set; }
        public string CommodityCartonCode { get; set; }
        public decimal Volume { get; set; }
        public int Shelflife { get; set; }
        public int PackPerCarton { get; set; }
        public int CartonPerPallet { get; set; }
    }
}
