//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class BatchMasterIndex
    {
        public int BatchMasterID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Reference { get; set; }
        public string BatchMasterCode { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityOfficialCode { get; set; }
        public string CommodityName { get; set; }
        public string CommodityAPICode { get; set; }
        public string CommodityCartonCode { get; set; }
        public decimal Volume { get; set; }
        public int PackPerCarton { get; set; }
        public int CartonPerPallet { get; set; }
        public int Shelflife { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> PackQuantity { get; set; }
        public Nullable<decimal> PackLineVolume { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime EditedDate { get; set; }
        public bool IsDefault { get; set; }
        public bool InActive { get; set; }
        public int BatchStatusID { get; set; }
        public string BatchStatusCode { get; set; }
        public decimal PlannedQuantity { get; set; }
        public Nullable<int> LotID { get; set; }
        public Nullable<System.DateTime> LotEntryDate { get; set; }
        public string LotCode { get; set; }
    }
}
