//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class PendingLot
    {
        public int BatchMasterID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string LotCode { get; set; }
        public decimal Volume { get; set; }
        public int PackPerCarton { get; set; }
        public int CartonPerPallet { get; set; }
        public int LotID { get; set; }
        public decimal PlannedQuantity { get; set; }
        public string BatchStatusCode { get; set; }
        public string Remarks { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public string CommodityAPICode { get; set; }
        public string CommodityCartonCode { get; set; }
        public string Code { get; set; }
        public int CommodityID { get; set; }
        public string NextPackNo { get; set; }
        public string NextCartonNo { get; set; }
        public string NextPalletNo { get; set; }
    }
}
