//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repack
    {
        public int RepackID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int BatchID { get; set; }
        public int PackID { get; set; }
        public int PrintedTimes { get; set; }
        public string Code { get; set; }
        public int SerialID { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Pack Pack { get; set; }
    }
}
